pipelines:
  - name: Pipeline_2
    configuration:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2
    steps:
      - name: Simple_Bash
        type: Bash
        execution:
          onStart:
            - cat "something working" >> file_1
            - add_pipeline_files test file_1
          onExecute:
            - mkdir -p testing
            - restore_pipeline_files file_1 ./testing/.
            - ls -l ./testing/

      - name: matrix_2
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: Simple_Bash
        matrix:
          environmentVariables:
            - env1: one
              env2: two
              env3: three
            - env1: changed1
              env2: changed2
            - key_1: value1
              key_2: value2
          runtimes:
            - type: image
              image:
                custom:
                  name: shippabledocker/jfreq
                  tag: latest
                  registry: i_docker
            - type: image
              image:
                custom:
                  name: shippabledocker/sample-node
                  tag: latest
                  registry: i_docker
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0
        execution:
          onExecute:
            - echo "I am on matrix step"